### ISSUE TITLE
Error while import

### ISSUE THREAD

**Issue by grach0v** [wang-ps/mesh2sdf#7]
Hello,
I install package via `pip install mesh2sdf` into `conda` environment  
But running `import mesh2sdf` gives me this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/denis/miniconda3/envs/robotics/lib/python3.12/site-packages/mesh2sdf/__init__.py", line 1, in <module>
    from .compute import compute
  File "/home/denis/miniconda3/envs/robotics/lib/python3.12/site-packages/mesh2sdf/compute.py", line 5, in <module>
    import mesh2sdf.core
ImportError: /home/denis/miniconda3/envs/robotics/lib/python3.12/site-packages/mesh2sdf/core.cpython-312-x86_64-linux-gnu.so: undefined symbol: __cxa_call_terminate
```

Any ideas how to fix this?
Thanks

**Comment by wang-ps** [comment]
C++ compilers are needed to install `mesh2sdf`.
Supported compilers are listed [here](https://github.com/pybind/pybind11#supported-compilers).

**Comment by grach0v** [comment]
I do have installed gcc, clang and llvm
```
$ gcc --version
gcc (GCC) 14.1.1 20240507
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version
clang version 17.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ llvm-config  --version
17.0.6
```
